name: audio_effects_sdk_example
description: Demonstrates how to use the audio_effects_sdk plugin.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.11.7

  audio_effects_sdk:
    path: ../

  cupertino_icons: ^1.0.2

flutter:

  uses-material-design: true